import './globals.css'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth/next'
import { Inter } from 'next/font/google'
import Provider from './Provider'
import { authOptions } from './api/auth/[...nextauth]/route'
import ReactQueryContext from '@/components/ReactQueryContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session: any = await getServerSession(authOptions)

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Bangers&family=Rubik:wght@400;600;800&family=Ysabeau:wght@200&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
        <link rel="icon" type="image/svg" href="/favicon.svg" />
        <meta name="theme-color" content="#060606" />
      </head>
      <Provider session={session}>
        <ReactQueryContext>
          <body className={inter.className}>{children}</body>
        </ReactQueryContext>
      </Provider>
    </html>
  )
}
